### ISSUE TITLE
Missing .dta preventing merge?

### ISSUE THREAD

**Issue by bholtdwyer** [wschpero/statastates#8]
. net install statastates, from(https://raw.github.com/wschpero/statastates/
> master/) replace
checking statastates consistency and verifying not already installed...

the following files will be replaced:
    /Users/holtdwyer/Library/Application Support/Stata/ado/plus/s/statastate
> s.ado

installing into /Users/holtdwyer/Library/Application Support/Stata/ado/plus/
> ...
installation complete.

. statastates, fips(state_fips) nogenerate
  (all newnames==oldnames)
file
    /Users/holtdwyer/Documents/Stata/ado/personal/statastates_data/statast
    > ates.dta not found
r(601);

When I try installing and running statastates, the only thing that happens is my variable becomes renamed state_fips, but no other changes are made, and I get an error saying statastates.dta not found.

**Comment by bholtdwyer** [comment]
Yes, that's not surprising. I'm using Stata on a shared server managed by
an administrator, so I don't necessarily have write permissions everywhere
I would on a personal machine. Is there a way to set the folder used to a
folder I know I have write access to?

**Comment by wschpero** [comment]
I believe you should be able to do it using the instructions here: https://kb.iu.edu/d/arur

Hope that helps!
